# Generated by Django 2.0.7 on 2018-07-30 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('business_addr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_addr', to='polls.Address')),
                ('home_addr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_addr', to='polls.Address')),
                ('other_addr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='other_addr', to='polls.Address')),
            ],
        ),
    ]
